/**
 * Comprehensive global location presets:
 * - Workplace modes (Remote Worldwide, Remote India, Remote US, etc.)
 * - Major tech hubs & metropolitan areas (India, US, UK, EU, UAE, APAC)
 * - Countries & regional hubs
 */

export const WORKPLACE_MODES = [
  "Remote (Worldwide)",
  "Remote (India)",
  "Remote (US & Canada)",
  "Remote (Europe)",
  "Remote (APAC / Middle East)",
  "Hybrid (Flexible)",
  "On-site / In-Office",
];

export const MAJOR_TECH_HUBS = [
  // India
  "Bangalore, Karnataka, India (Hybrid)",
  "Bangalore, Karnataka, India (On-site)",
  "Hyderabad, Telangana, India (Hybrid)",
  "Hyderabad, Telangana, India (On-site)",
  "Pune, Maharashtra, India (Hybrid)",
  "Pune, Maharashtra, India (On-site)",
  "Mumbai, Maharashtra, India (Hybrid)",
  "Gurgaon / Delhi NCR, India (Hybrid)",
  "Noida / Delhi NCR, India (Hybrid)",
  "Delhi, India (Hybrid)",
  "Chennai, Tamil Nadu, India (Hybrid)",
  "Chennai, Tamil Nadu, India (On-site)",
  "Kolkata, West Bengal, India (Hybrid)",
  "Ahmedabad, Gujarat, India (Hybrid)",
  "Kochi, Kerala, India (Hybrid)",
  "Trivandrum, Kerala, India (Hybrid)",
  "Coimbatore, Tamil Nadu, India",
  "Chandigarh / Mohali, India",
  "Jaipur, Rajasthan, India",
  "Indore, Madhya Pradesh, India",
  "Bhubaneswar, Odisha, India",

  // United States & Canada
  "San Francisco, CA, United States (Hybrid)",
  "San Francisco Bay Area / Silicon Valley, CA",
  "New York, NY, United States (Hybrid)",
  "Austin, TX, United States (Hybrid)",
  "Seattle, WA, United States (Hybrid)",
  "Boston, MA, United States",
  "Los Angeles, CA, United States",
  "Chicago, IL, United States",
  "Denver, CO, United States",
  "Atlanta, GA, United States",
  "Washington, DC, United States",
  "Dallas / Fort Worth, TX, United States",
  "Toronto, ON, Canada (Hybrid)",
  "Vancouver, BC, Canada (Hybrid)",
  "Montreal, QC, Canada",
  "Ottawa, ON, Canada",

  // United Kingdom & Europe
  "London, England, United Kingdom (Hybrid)",
  "London, England, United Kingdom (On-site)",
  "Manchester, United Kingdom",
  "Dublin, Ireland (Hybrid)",
  "Berlin, Germany (Hybrid)",
  "Munich, Germany",
  "Frankfurt, Germany",
  "Amsterdam, Netherlands (Hybrid)",
  "Paris, France (Hybrid)",
  "Stockholm, Sweden",
  "Zurich, Switzerland",
  "Geneva, Switzerland",
  "Madrid, Spain",
  "Barcelona, Spain",
  "Warsaw, Poland",
  "Krakow, Poland",

  // Middle East
  "Dubai, United Arab Emirates (Hybrid)",
  "Dubai, United Arab Emirates (On-site)",
  "Abu Dhabi, United Arab Emirates",
  "Riyadh, Saudi Arabia (Hybrid)",
  "Jeddah, Saudi Arabia",
  "Doha, Qatar",

  // Asia-Pacific
  "Singapore (Hybrid)",
  "Singapore (On-site)",
  "Sydney, NSW, Australia (Hybrid)",
  "Melbourne, VIC, Australia (Hybrid)",
  "Brisbane, QLD, Australia",
  "Auckland, New Zealand",
  "Tokyo, Japan",
  "Seoul, South Korea",
  "Hong Kong",
  "Kuala Lumpur, Malaysia",
  "Jakarta, Indonesia",
  "Bangkok, Thailand",
  "Manila, Philippines",
];

export const INDIAN_STATES = [
  "Andhra Pradesh, India",
  "Arunachal Pradesh, India",
  "Assam, India",
  "Bihar, India",
  "Chhattisgarh, India",
  "Goa, India",
  "Gujarat, India",
  "Haryana, India",
  "Himachal Pradesh, India",
  "Jharkhand, India",
  "Karnataka, India",
  "Kerala, India",
  "Madhya Pradesh, India",
  "Maharashtra, India",
  "Manipur, India",
  "Meghalaya, India",
  "Mizoram, India",
  "Nagaland, India",
  "Odisha, India",
  "Punjab, India",
  "Rajasthan, India",
  "Sikkim, India",
  "Tamil Nadu, India",
  "Telangana, India",
  "Tripura, India",
  "Uttar Pradesh, India",
  "Uttarakhand, India",
  "West Bengal, India",
  "Delhi (NCT), India",
  "Chandigarh (UT), India",
];

export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "India",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Netherlands",
  "Ireland",
  "Switzerland",
  "United Arab Emirates",
  "Saudi Arabia",
  "Singapore",
  "Japan",
  "South Korea",
  "Sweden",
  "Spain",
  "Italy",
  "Poland",
  "Brazil",
  "Mexico",
  "South Africa",
  "New Zealand",
  "Norway",
  "Denmark",
  "Finland",
  "Belgium",
  "Austria",
  "Portugal",
  "Israel",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Indonesia",
  "Malaysia",
  "Thailand",
  "Vietnam",
  "Philippines",
  "Argentina",
  "Chile",
  "Colombia",
];

export const ALL_LOCATION_PRESETS = [
  ...WORKPLACE_MODES,
  ...MAJOR_TECH_HUBS,
  ...INDIAN_STATES,
  ...COUNTRIES,
];
