// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockJobs as seedJobs, mockCandidates as seedCandidates } from '../../data/mockData';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder';

// Real client
const realSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

let globalNeedsPasswordReset = false;
realSupabase.auth.onAuthStateChange((event) => {
  if (event === 'PASSWORD_RECOVERY') {
    globalNeedsPasswordReset = true;
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new Event('password_recovery_event'));
    }
  }
});

export function getNeedsPasswordReset() {
  return globalNeedsPasswordReset;
}

// Mock state management keys
const MOCK_USERS_KEY = 'hiremate_mock_users';
const MOCK_PROFILES_KEY = 'hiremate_mock_profiles';
const MOCK_ROLES_KEY = 'hiremate_mock_roles';
const MOCK_SESSION_KEY = 'hiremate_mock_session';
const USE_MOCK_SUPABASE_KEY = 'use_mock_supabase';
const MOCK_JOBS_KEY = 'hiremate_mock_jobs';
const MOCK_CANDIDATES_KEY = 'hiremate_mock_candidates';

let useMock = localStorage.getItem(USE_MOCK_SUPABASE_KEY) === 'true';

// Local mock database helper functions
function getMockJobs() {
  const data = localStorage.getItem(MOCK_JOBS_KEY);
  if (!data) {
    localStorage.setItem(MOCK_JOBS_KEY, JSON.stringify(seedJobs));
    return seedJobs;
  }
  return JSON.parse(data);
}

function saveMockJobs(jobs: any[]) {
  localStorage.setItem(MOCK_JOBS_KEY, JSON.stringify(jobs));
}

function getMockCandidates() {
  const data = localStorage.getItem(MOCK_CANDIDATES_KEY);
  if (!data) {
    localStorage.setItem(MOCK_CANDIDATES_KEY, JSON.stringify(seedCandidates));
    return seedCandidates;
  }
  return JSON.parse(data);
}

function saveMockCandidates(candidates: any[]) {
  localStorage.setItem(MOCK_CANDIDATES_KEY, JSON.stringify(candidates));
}

// Helper to switch to mock mode
export function enableMockMode() {
  if (!useMock) {
    useMock = true;
    localStorage.setItem(USE_MOCK_SUPABASE_KEY, 'true');
    window.dispatchEvent(new Event('supabase_mock_mode_enabled'));
  }
}

// Check if mock mode is active
export function isMockMode() {
  return useMock;
}

// Check if we should disable mock mode (e.g. if explicitly cleared)
export function disableMockMode() {
  useMock = false;
  localStorage.removeItem(USE_MOCK_SUPABASE_KEY);
  localStorage.removeItem(MOCK_SESSION_KEY);
  window.dispatchEvent(new Event('supabase_mock_mode_disabled'));
}

// Check if current error is a network connectivity error
function isNetworkError(err: any): boolean {
  if (!err) return false;
  const msg = String(err.message || err).toLowerCase();
  return (
    msg.includes('failed to fetch') ||
    msg.includes('network error') ||
    msg.includes('load failed') ||
    msg.includes('dns') ||
    msg.includes('connection') ||
    msg.includes('unreachable') ||
    msg.includes('cors')
  );
}

// Local mock database helpers
function getMockUsers() {
  const data = localStorage.getItem(MOCK_USERS_KEY);
  return data ? JSON.parse(data) : [];
}

function saveMockUsers(users: any[]) {
  localStorage.setItem(MOCK_USERS_KEY, JSON.stringify(users));
}

function getMockProfiles() {
  const data = localStorage.getItem(MOCK_PROFILES_KEY);
  return data ? JSON.parse(data) : [];
}

function saveMockProfiles(profiles: any[]) {
  localStorage.setItem(MOCK_PROFILES_KEY, JSON.stringify(profiles));
}

function getMockRoles() {
  const data = localStorage.getItem(MOCK_ROLES_KEY);
  return data ? JSON.parse(data) : [];
}

function saveMockRoles(roles: any[]) {
  localStorage.setItem(MOCK_ROLES_KEY, JSON.stringify(roles));
}

function getMockSession() {
  const data = localStorage.getItem(MOCK_SESSION_KEY);
  return data ? JSON.parse(data) : null;
}

function setMockSession(user: any) {
  const session = {
    access_token: 'mock-access-token',
    token_type: 'bearer',
    expires_in: 3600,
    refresh_token: 'mock-refresh-token',
    user: user,
    expires_at: Math.floor(Date.now() / 1000) + 3600
  };
  localStorage.setItem(MOCK_SESSION_KEY, JSON.stringify(session));
}

function clearMockSession() {
  localStorage.removeItem(MOCK_SESSION_KEY);
}

function createMockUser(email: string, fullName: string) {
  const id = 'mock-user-id-' + Math.random().toString(36).substring(2, 11);
  const user = {
    id,
    aud: 'authenticated',
    role: 'authenticated',
    email,
    email_confirmed_at: new Date().toISOString(),
    phone: '',
    confirmed_at: new Date().toISOString(),
    last_sign_in_at: new Date().toISOString(),
    app_metadata: { provider: 'email', providers: ['email'] },
    user_metadata: { full_name: fullName },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };

  const users = getMockUsers();
  users.push(user);
  saveMockUsers(users);

  // Add profile
  const profiles = getMockProfiles();
  profiles.push({
    id,
    email,
    full_name: fullName,
    avatar_url: `https://api.dicebear.com/7.x/adventurer/svg?seed=${encodeURIComponent(fullName)}`,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  });
  saveMockProfiles(profiles);

  // Add user role
  const roles = getMockRoles();
  // If first user, make them admin
  const role = roles.length === 0 ? 'admin' : 'recruiter';
  roles.push({
    id: 'mock-role-id-' + Math.random().toString(36).substring(2, 11),
    user_id: id,
    role,
    created_at: new Date().toISOString()
  });
  saveMockRoles(roles);

  return user;
}

let mockAuthListeners: any[] = [];
function triggerAuthChange(event: string, session: any) {
  mockAuthListeners.forEach(listener => {
    try {
      listener(event, session);
    } catch (e) {
      console.error('Error in auth state change listener:', e);
    }
  });
}

// Seed initial mock users if lists are empty
if (getMockUsers().length === 0) {
  createMockUser('admin@hiremate.ai', 'Administrator');
  createMockUser('recruiter@hiremate.ai', 'Jane Recruiter');
}

// Mock query builder to mimic postgrest
class MockQueryBuilder {
  table: string;
  filters: Array<(item: any) => boolean> = [];
  updateData: any = null;
  isDelete: boolean = false;

  constructor(table: string) {
    this.table = table;
  }

  select(columns?: string) {
    return this;
  }

  delete() {
    this.isDelete = true;
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push((item) => item[column] === value);
    return this;
  }

  neq(column: string, value: any) {
    this.filters.push((item) => item[column] !== value);
    return this;
  }

  in(column: string, values: any[]) {
    this.filters.push((item) => values.includes(item[column]));
    return this;
  }

  maybeSingle() {
    return this.execute().then(res => ({
      data: res.data && res.data.length > 0 ? res.data[0] : null,
      error: res.error
    }));
  }

  single() {
    return this.execute().then(res => {
      if (!res.data || res.data.length === 0) {
        return { data: null, error: new Error('No rows found') };
      }
      return { data: res.data[0], error: null };
    });
  }

  update(data: any) {
    this.updateData = data;
    return this;
  }

  insert(data: any) {
    this.updateData = data; // use insert mode
    this.filters = []; // clear filters for insert
    return this;
  }

  async execute() {
    if (this.isDelete) {
      let data: any[] = [];
      if (this.table === 'jobs') {
        let jobs = getMockJobs();
        if (this.filters.length > 0) {
          jobs = jobs.filter(j => {
            let matches = true;
            for (const filter of this.filters) {
              if (!filter(j)) matches = false;
            }
            return !matches;
          });
        } else {
          jobs = [];
        }
        saveMockJobs(jobs);
      } else if (this.table === 'candidates') {
        let candidates = getMockCandidates();
        if (this.filters.length > 0) {
          candidates = candidates.filter(c => {
            let matches = true;
            for (const filter of this.filters) {
              if (!filter(c)) matches = false;
            }
            return !matches;
          });
        } else {
          candidates = [];
        }
        saveMockCandidates(candidates);
      }
      return { data, error: null };
    }

    let data: any[] = [];
    if (this.table === 'profiles') {
      data = getMockProfiles();
    } else if (this.table === 'user_roles') {
      data = getMockRoles();
    } else if (this.table === 'jobs') {
      data = getMockJobs();
    } else if (this.table === 'candidates') {
      data = getMockCandidates();
    }

    if (this.updateData) {
      if (this.table === 'profiles') {
        let profiles = getMockProfiles();
        let updated = false;
        profiles = profiles.map(p => {
          let matches = this.filters.length > 0;
          for (const filter of this.filters) {
            if (!filter(p)) matches = false;
          }
          if (matches) {
            updated = true;
            return { ...p, ...this.updateData, updated_at: new Date().toISOString() };
          }
          return p;
        });

        if (!updated && this.filters.length === 0) {
          // Insert mode
          const newProfile = {
            id: this.updateData.id || 'mock-id-' + Math.random().toString(36).substring(2, 11),
            email: this.updateData.email || null,
            full_name: this.updateData.full_name || null,
            avatar_url: this.updateData.avatar_url || null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          };
          profiles.push(newProfile);
          data = [newProfile];
        } else {
          data = profiles.filter(p => {
            let matches = this.filters.length > 0;
            for (const filter of this.filters) {
              if (!filter(p)) matches = false;
            }
            return matches;
          });
        }
        saveMockProfiles(profiles);
      } else if (this.table === 'user_roles') {
        let roles = getMockRoles();
        let updated = false;
        roles = roles.map(r => {
          let matches = this.filters.length > 0;
          for (const filter of this.filters) {
            if (!filter(r)) matches = false;
          }
          if (matches) {
            updated = true;
            return { ...r, ...this.updateData };
          }
          return r;
        });

        if (!updated && this.filters.length === 0) {
          // Insert mode
          const newRole = {
            id: 'mock-role-id-' + Math.random().toString(36).substring(2, 11),
            user_id: this.updateData.user_id,
            role: this.updateData.role || 'recruiter',
            created_at: new Date().toISOString()
          };
          roles.push(newRole);
          data = [newRole];
        } else {
          data = roles.filter(r => {
            let matches = this.filters.length > 0;
            for (const filter of this.filters) {
              if (!filter(r)) matches = false;
            }
            return matches;
          });
        }
        saveMockRoles(roles);
      } else if (this.table === 'jobs') {
        let jobs = getMockJobs();
        let updated = false;
        jobs = jobs.map(j => {
          let matches = this.filters.length > 0;
          for (const filter of this.filters) {
            if (!filter(j)) matches = false;
          }
          if (matches) {
            updated = true;
            return { ...j, ...this.updateData };
          }
          return j;
        });

        if (!updated && this.filters.length === 0) {
          const newJob = {
            id: 'job-' + Math.random().toString(36).substring(2, 9),
            title: this.updateData.title,
            department: this.updateData.department || 'General',
            location: this.updateData.location || 'Remote',
            type: this.updateData.type || 'full-time',
            postedDate: new Date().toISOString().split('T')[0],
            screeningEndDate: this.updateData.screeningEndDate || null,
            status: 'active',
            candidateCount: 0,
            hireSortEnabled: false,
            description: this.updateData.description || '',
            responsibilities: this.updateData.responsibilities || [],
            requirements: this.updateData.requirements || [],
            niceToHave: this.updateData.niceToHave || [],
            salary: this.updateData.salary || 'Competitive',
            predictiveEffectiveness: this.updateData.predictiveEffectiveness || null
          };
          jobs.push(newJob);
          data = [newJob];
        } else {
          data = jobs.filter(j => {
            let matches = this.filters.length > 0;
            for (const filter of this.filters) {
              if (!filter(j)) matches = false;
            }
            return matches;
          });
        }
        saveMockJobs(jobs);
      } else if (this.table === 'candidates') {
        let candidates = getMockCandidates();
        let updated = false;
        candidates = candidates.map(c => {
          let matches = this.filters.length > 0;
          for (const filter of this.filters) {
            if (!filter(c)) matches = false;
          }
          if (matches) {
            updated = true;
            return { ...c, ...this.updateData };
          }
          return c;
        });

        if (!updated && this.filters.length === 0) {
          const newCandidate = {
            id: 'cand-' + Math.random().toString(36).substring(2, 9),
            name: this.updateData.name || this.updateData.full_name || 'Anonymous Applicant',
            email: this.updateData.email || 'anonymous@example.com',
            experience: Number(this.updateData.experience) || 0,
            location: this.updateData.location || 'Remote',
            appliedDate: new Date().toISOString().split('T')[0],
            matchedSkills: this.updateData.matchedSkills || [],
            missingSkills: this.updateData.missingSkills || [],
            aiScore: this.updateData.aiScore || 'medium',
            cosineSimilarity: this.updateData.cosineSimilarity || 0.6,
            predictiveInsights: this.updateData.predictiveInsights || {},
            resumeUrl: this.updateData.resumeUrl || null,
            resumeText: this.updateData.resumeText || ''
          };
          candidates.push(newCandidate);
          data = [newCandidate];
        } else {
          data = candidates.filter(c => {
            let matches = this.filters.length > 0;
            for (const filter of this.filters) {
              if (!filter(c)) matches = false;
            }
            return matches;
          });
        }
        saveMockCandidates(candidates);
      }
    } else {
      // Standard filter (select)
      if (this.filters.length > 0) {
        data = data.filter(item => {
          let matches = true;
          for (const filter of this.filters) {
            if (!filter(item)) matches = false;
          }
          return matches;
        });
      }
    }

    return { data, error: null };
  }

  then(onfulfilled?: any, onrejected?: any) {
    return this.execute().then(onfulfilled, onrejected);
  }
}

// Mock Supabase Client Object
const mockSupabase = {
  auth: {
    onAuthStateChange(callback: any) {
      mockAuthListeners.push(callback);
      const session = getMockSession();
      setTimeout(() => {
        callback(session ? 'SIGNED_IN' : 'SIGNED_OUT', session);
      }, 0);
      return {
        data: {
          subscription: {
            unsubscribe() {
              mockAuthListeners = mockAuthListeners.filter(l => l !== callback);
            }
          }
        }
      };
    },
    async getSession() {
      return { data: { session: getMockSession() }, error: null };
    },
    async signInWithPassword({ email, password }: any) {
      if (!email.includes('@')) {
        return { data: { session: null, user: null }, error: new Error('Invalid email format') };
      }
      if (password.length < 6) {
        return { data: { session: null, user: null }, error: new Error('Password must be at least 6 characters') };
      }
      
      const users = getMockUsers();
      let user = users.find(u => u.email === email);
      if (!user) {
        // If email matches one of the seeded users but isn't registered, create it
        if (email === 'admin@hiremate.ai') {
          user = createMockUser('admin@hiremate.ai', 'Administrator');
        } else if (email === 'recruiter@hiremate.ai') {
          user = createMockUser('recruiter@hiremate.ai', 'Jane Recruiter');
        } else {
          // Allow automatic signup for any emails to make local dev super easy
          user = createMockUser(email, email.split('@')[0]);
        }
      }
      
      setMockSession(user);
      triggerAuthChange('SIGNED_IN', getMockSession());
      return { data: { session: getMockSession(), user }, error: null };
    },
    async signUp({ email, password, options }: any) {
      if (password.length < 6) {
        return { data: { session: null, user: null }, error: new Error('Password must be at least 6 characters') };
      }
      const users = getMockUsers();
      if (users.some(u => u.email === email)) {
        return { data: { session: null, user: null }, error: new Error('User already registered') };
      }
      
      const fullName = options?.data?.full_name || email.split('@')[0];
      const user = createMockUser(email, fullName);
      setMockSession(user);
      triggerAuthChange('SIGNED_IN', getMockSession());
      return { data: { session: getMockSession(), user }, error: null };
    },
    async signOut() {
      clearMockSession();
      triggerAuthChange('SIGNED_OUT', null);
      return { error: null };
    }
  },
  from(table: string) {
    return new MockQueryBuilder(table);
  }
};

// Helper to wrap real database query builder chain
function wrapQueryBuilder(queryBuilder: any, table: string): any {
  return new Proxy(queryBuilder, {
    get(target: any, prop: string): any {
      const val = target[prop];
      if (typeof val === 'function') {
        return (...args: any[]) => {
          const res = val.apply(target, args);
          if (res && (typeof res === 'object' || typeof res === 'function')) {
            return wrapQueryBuilder(res, table);
          }
          return res;
        };
      }
      if (prop === 'then') {
        return (onfulfilled: any, onrejected: any) => {
          return target.then(
            (val: any) => {
              if (val && val.error && isNetworkError(val.error)) {
                console.warn(`Supabase query network error on ${table}, switching to mock mode.`, val.error);
                enableMockMode();
                return mockSupabase.from(table).execute().then(onfulfilled, onrejected);
              }
              return onfulfilled ? onfulfilled(val) : val;
            },
            (err: any) => {
              if (isNetworkError(err)) {
                console.warn(`Supabase query exception on ${table}, switching to mock mode.`, err);
                enableMockMode();
                return mockSupabase.from(table).execute().then(onfulfilled, onrejected);
              }
              return onrejected ? onrejected(err) : Promise.reject(err);
            }
          );
        };
      }
      return val;
    }
  });
}

// Proxied supabase client
export const supabase = new Proxy(realSupabase, {
  get(target: any, prop: string): any {
    if (useMock) {
      return (mockSupabase as any)[prop];
    }
    
    if (prop === 'auth') {
      return authProxy;
    }
    
    if (prop === 'from') {
      return (table: string) => {
        if (useMock) {
          return mockSupabase.from(table);
        }
        return wrapQueryBuilder(realSupabase.from(table), table);
      };
    }
    
    const val = target[prop];
    if (typeof val === 'function') {
      return (...args: any[]) => {
        try {
          const res = val.apply(target, args);
          if (res instanceof Promise) {
            return res.then((resolvedVal: any) => {
              if (resolvedVal && resolvedVal.error && isNetworkError(resolvedVal.error)) {
                console.warn("Supabase network error in response, switching to mock mode.", resolvedVal.error);
                enableMockMode();
                return (mockSupabase as any)[prop](...args);
              }
              return resolvedVal;
            }).catch((err) => {
              if (isNetworkError(err)) {
                console.warn("Supabase network error exception, switching to mock mode.", err);
                enableMockMode();
                return (mockSupabase as any)[prop](...args);
              }
              throw err;
            });
          }
          return res;
        } catch (err) {
          if (isNetworkError(err)) {
            console.warn("Supabase network error caught, switching to mock mode.", err);
            enableMockMode();
            return (mockSupabase as any)[prop](...args);
          }
          throw err;
        }
      };
    }
    return val;
  }
});

// Proxied auth client
const authProxy = new Proxy(realSupabase.auth, {
  get(target: any, prop: string): any {
    if (useMock) {
      return (mockSupabase.auth as any)[prop];
    }
    
    const val = target[prop];
    if (typeof val === 'function') {
      return (...args: any[]) => {
        try {
          const res = val.apply(target, args);
          if (res instanceof Promise) {
            return res.then((resolvedVal: any) => {
              if (resolvedVal && resolvedVal.error && isNetworkError(resolvedVal.error)) {
                console.warn("Supabase auth network error in response, switching to mock mode.", resolvedVal.error);
                enableMockMode();
                return (mockSupabase.auth as any)[prop](...args);
              }
              return resolvedVal;
            }).catch((err) => {
              if (isNetworkError(err)) {
                console.warn("Supabase auth network error exception, switching to mock mode.", err);
                enableMockMode();
                return (mockSupabase.auth as any)[prop](...args);
              }
              throw err;
            });
          }
          return res;
        } catch (err) {
          if (isNetworkError(err)) {
            console.warn("Supabase auth network error caught, switching to mock mode.", err);
            enableMockMode();
            return (mockSupabase.auth as any)[prop](...args);
          }
          throw err;
        }
      };
    }
    return val;
  }
});