// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { mockJobs as seedJobs, mockCandidates as seedCandidates } from '../../data/mockData';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder';

// Real client
const realSupabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

let globalNeedsPasswordReset = false;
realSupabase.auth.onAuthStateChange((event) => {
  if (event === 'PASSWORD_RECOVERY') {
    globalNeedsPasswordReset = true;
    if (typeof window !== 'undefined') {
      window.dispatchEvent(new Event('password_recovery_event'));
    }
  }
});

export function getNeedsPasswordReset() {
  return globalNeedsPasswordReset;
}

// Mock state management keys
const MOCK_USERS_KEY = 'hiremate_mock_users';
const MOCK_PROFILES_KEY = 'hiremate_mock_profiles';
const MOCK_ROLES_KEY = 'hiremate_mock_roles';
const MOCK_SESSION_KEY = 'hiremate_mock_session';
const USE_MOCK_SUPABASE_KEY = 'use_mock_supabase';
const MOCK_JOBS_KEY = 'hiremate_mock_jobs';
const MOCK_CANDIDATES_KEY = 'hiremate_mock_candidates';

export const hasRealSupabase = Boolean(SUPABASE_URL && !SUPABASE_URL.includes('placeholder'));

let useMock = typeof localStorage !== 'undefined' && localStorage.getItem(USE_MOCK_SUPABASE_KEY) === 'true';

const DEFAULT_ZOOL_ID = '00000000-0000-0000-0000-000000000001';
const DEFAULT_COMMIT_ID = '00000000-0000-0000-0000-000000000004';

const INITIAL_MOCK_JOBS = [
  // Zool Tenant Jobs
  {
    id: '11111111-1111-1111-1111-111111111111',
    title: 'Senior Frontend Engineer',
    department: 'Engineering',
    location: 'Bangalore, India',
    type: 'full-time',
    postedDate: '2024-01-08',
    status: 'active',
    candidateCount: 5,
    hireSortEnabled: true,
    hire_sort_enabled: true,
    salary: '₹35-50 LPA',
    client_id: DEFAULT_ZOOL_ID,
    description: 'Lead the frontend architecture of our flagship product with React & TypeScript.',
    requirements: ['React 18 & TypeScript (5+ years)', 'State Management', 'Testing'],
    responsibilities: ['Architect scalable frontend systems', 'Mentor junior developers'],
    created_at: '2024-01-08T00:00:00.000Z'
  },
  {
    id: '22222222-2222-2222-2222-222222222222',
    title: 'Product Manager',
    department: 'Product',
    location: 'Singapore',
    type: 'full-time',
    postedDate: '2024-01-12',
    status: 'active',
    candidateCount: 4,
    hireSortEnabled: true,
    hire_sort_enabled: true,
    salary: '$110,000 - $140,000',
    client_id: DEFAULT_ZOOL_ID,
    description: 'Own core product roadmap and feature delivery across global markets.',
    requirements: ['4+ years SaaS Product Management', 'Data analytics', 'Agile'],
    responsibilities: ['Define roadmap', 'Write PRDs', 'Track key metrics'],
    created_at: '2024-01-12T00:00:00.000Z'
  },
  {
    id: '33333333-3333-3333-3333-333333333333',
    title: 'UX Designer',
    department: 'Design',
    location: 'Remote',
    type: 'full-time',
    postedDate: '2024-01-15',
    status: 'active',
    candidateCount: 3,
    hireSortEnabled: true,
    hire_sort_enabled: true,
    salary: '$80,000 - $105,000',
    client_id: DEFAULT_ZOOL_ID,
    description: 'Craft intuitive interfaces and design systems for enterprise web applications.',
    requirements: ['3+ years Figma & UX prototyping', 'Design systems', 'WCAG accessibility'],
    responsibilities: ['Create UI prototypes', 'Conduct usability testing'],
    created_at: '2024-01-15T00:00:00.000Z'
  },
  // Commit Tenant Jobs
  {
    id: '44444444-4444-4444-4444-444444444444',
    title: 'Full Stack Developer',
    department: 'Engineering',
    location: 'San Francisco, CA',
    type: 'full-time',
    postedDate: '2024-01-18',
    status: 'active',
    candidateCount: 4,
    hireSortEnabled: true,
    hire_sort_enabled: true,
    salary: '$130,000 - $160,000',
    client_id: DEFAULT_COMMIT_ID,
    description: 'Build robust enterprise services using TypeScript, Node.js, and React.',
    requirements: ['TypeScript & Node.js', 'PostgreSQL', 'Cloud Infrastructure'],
    responsibilities: ['Build full stack features', 'Optimize SQL queries'],
    created_at: '2024-01-18T00:00:00.000Z'
  },
  {
    id: '55555555-5555-5555-5555-555555555555',
    title: 'Enterprise Marketing Director',
    department: 'Marketing',
    location: 'New York, NY',
    type: 'full-time',
    postedDate: '2024-01-20',
    status: 'active',
    candidateCount: 3,
    hireSortEnabled: true,
    hire_sort_enabled: true,
    salary: '$120,000 - $150,000',
    client_id: DEFAULT_COMMIT_ID,
    description: 'Lead enterprise demand generation, product marketing, and brand strategy.',
    requirements: ['B2B SaaS Growth (5+ years)', 'Demand Generation', 'Brand leadership'],
    responsibilities: ['Drive enterprise pipeline', 'Manage marketing budgets'],
    created_at: '2024-01-20T00:00:00.000Z'
  },
  {
    id: '66666666-6666-6666-6666-666666666666',
    title: 'Cloud Security Engineer',
    department: 'Security',
    location: 'Austin, TX',
    type: 'full-time',
    postedDate: '2024-01-22',
    status: 'active',
    candidateCount: 2,
    hireSortEnabled: true,
    hire_sort_enabled: true,
    salary: '$140,000 - $175,000',
    client_id: DEFAULT_COMMIT_ID,
    description: 'Secure multi-tenant cloud environments and ensure SOC2 and GDPR compliance.',
    requirements: ['AWS / GCP security (4+ years)', 'Kubernetes hardening', 'Compliance standards'],
    responsibilities: ['Conduct vulnerability scans', 'Enforce IAM policies'],
    created_at: '2024-01-22T00:00:00.000Z'
  }
];

const INITIAL_MOCK_CANDIDATES = [
  // Zool Candidates
  {
    id: 'cand-z1',
    job_id: '11111111-1111-1111-1111-111111111111',
    full_name: 'Priya Sharma',
    email: 'priya.sharma@example.com',
    experience: 6,
    location: 'Bangalore, India',
    ai_score: 'high',
    aiScore: 'high',
    cosine_similarity: 0.94,
    cosineSimilarity: 0.94,
    status: 'shortlisted',
    is_pinned: true,
    client_id: DEFAULT_ZOOL_ID,
    created_at: '2024-01-10T10:00:00.000Z'
  },
  {
    id: 'cand-z2',
    job_id: '11111111-1111-1111-1111-111111111111',
    full_name: 'David Chen',
    email: 'david.chen@example.com',
    experience: 5,
    location: 'Singapore',
    ai_score: 'high',
    aiScore: 'high',
    cosine_similarity: 0.88,
    cosineSimilarity: 0.88,
    status: 'interviewing',
    client_id: DEFAULT_ZOOL_ID,
    created_at: '2024-01-12T14:30:00.000Z'
  },
  {
    id: 'cand-z3',
    job_id: '22222222-2222-2222-2222-222222222222',
    full_name: 'Elena Rostova',
    email: 'elena.rostova@example.com',
    experience: 7,
    location: 'Remote',
    ai_score: 'high',
    aiScore: 'high',
    cosine_similarity: 0.86,
    cosineSimilarity: 0.86,
    status: 'shortlisted',
    client_id: DEFAULT_ZOOL_ID,
    created_at: '2024-01-14T09:15:00.000Z'
  },
  {
    id: 'cand-z4',
    job_id: '33333333-3333-3333-3333-333333333333',
    full_name: 'Amit Patel',
    email: 'amit.patel@example.com',
    experience: 4,
    location: 'Mumbai, India',
    ai_score: 'medium',
    aiScore: 'medium',
    cosine_similarity: 0.72,
    cosineSimilarity: 0.72,
    status: 'pending',
    client_id: DEFAULT_ZOOL_ID,
    created_at: '2024-01-16T11:45:00.000Z'
  },
  {
    id: 'cand-z5',
    job_id: '22222222-2222-2222-2222-222222222222',
    full_name: 'Sofia Rossi',
    email: 'sofia.rossi@example.com',
    experience: 3,
    location: 'Milan, Italy',
    ai_score: 'medium',
    aiScore: 'medium',
    cosine_similarity: 0.69,
    cosineSimilarity: 0.69,
    status: 'pending',
    client_id: DEFAULT_ZOOL_ID,
    created_at: '2024-01-18T16:20:00.000Z'
  },

  // Commit Candidates
  {
    id: 'cand-c1',
    job_id: '44444444-4444-4444-4444-444444444444',
    full_name: 'Marcus Vance',
    email: 'marcus.vance@example.com',
    experience: 6,
    location: 'San Francisco, CA',
    ai_score: 'high',
    aiScore: 'high',
    cosine_similarity: 0.95,
    cosineSimilarity: 0.95,
    status: 'shortlisted',
    is_pinned: true,
    client_id: DEFAULT_COMMIT_ID,
    created_at: '2024-01-19T08:30:00.000Z'
  },
  {
    id: 'cand-c2',
    job_id: '55555555-5555-5555-5555-555555555555',
    full_name: 'Sarah Jenkins',
    email: 'sarah.jenkins@example.com',
    experience: 8,
    location: 'New York, NY',
    ai_score: 'high',
    aiScore: 'high',
    cosine_similarity: 0.90,
    cosineSimilarity: 0.90,
    status: 'interviewing',
    client_id: DEFAULT_COMMIT_ID,
    created_at: '2024-01-21T10:15:00.000Z'
  },
  {
    id: 'cand-c3',
    job_id: '66666666-6666-6666-6666-666666666666',
    full_name: 'Liam O\'Connor',
    email: 'liam.oconnor@example.com',
    experience: 5,
    location: 'Austin, TX',
    ai_score: 'high',
    aiScore: 'high',
    cosine_similarity: 0.88,
    cosineSimilarity: 0.88,
    status: 'shortlisted',
    client_id: DEFAULT_COMMIT_ID,
    created_at: '2024-01-23T12:00:00.000Z'
  },
  {
    id: 'cand-c4',
    job_id: '44444444-4444-4444-4444-444444444444',
    full_name: 'Maya Lin',
    email: 'maya.lin@example.com',
    experience: 4,
    location: 'Seattle, WA',
    ai_score: 'medium',
    aiScore: 'medium',
    cosine_similarity: 0.77,
    cosineSimilarity: 0.77,
    status: 'pending',
    client_id: DEFAULT_COMMIT_ID,
    created_at: '2024-01-24T14:45:00.000Z'
  },
  {
    id: 'cand-c5',
    job_id: '66666666-6666-6666-6666-666666666666',
    full_name: 'Ethan Hunt',
    email: 'ethan.hunt@example.com',
    experience: 5,
    location: 'Dallas, TX',
    ai_score: 'medium',
    aiScore: 'medium',
    cosine_similarity: 0.71,
    cosineSimilarity: 0.71,
    status: 'pending',
    client_id: DEFAULT_COMMIT_ID,
    created_at: '2024-01-25T11:10:00.000Z'
  },
  {
    id: 'cand-c6',
    job_id: '55555555-5555-5555-5555-555555555555',
    full_name: 'Chloe Bennett',
    email: 'chloe.bennett@example.com',
    experience: 6,
    location: 'Chicago, IL',
    ai_score: 'high',
    aiScore: 'high',
    cosine_similarity: 0.92,
    cosineSimilarity: 0.92,
    status: 'interviewing',
    client_id: DEFAULT_COMMIT_ID,
    created_at: '2024-01-26T15:30:00.000Z'
  }
];

// Local mock database helper functions
function getMockJobs() {
  if (typeof localStorage === 'undefined') return INITIAL_MOCK_JOBS;
  const data = localStorage.getItem(MOCK_JOBS_KEY);
  if (!data) {
    localStorage.setItem(MOCK_JOBS_KEY, JSON.stringify(INITIAL_MOCK_JOBS));
    return INITIAL_MOCK_JOBS;
  }
  try {
    let parsed = JSON.parse(data);
    if (Array.isArray(parsed) && parsed.length > 0) {
      // Ensure any jobs without client_id are assigned to Zool
      parsed = parsed.map((j: any) => ({
        ...j,
        client_id: j.client_id || DEFAULT_ZOOL_ID
      }));
      // Ensure Commit tenant has its jobs
      const hasCommit = parsed.some((j: any) => j.client_id === DEFAULT_COMMIT_ID);
      if (!hasCommit) {
        parsed.push(...INITIAL_MOCK_JOBS.filter(j => j.client_id === DEFAULT_COMMIT_ID));
      }
      localStorage.setItem(MOCK_JOBS_KEY, JSON.stringify(parsed));
      return parsed;
    }
  } catch (e) {}
  localStorage.setItem(MOCK_JOBS_KEY, JSON.stringify(INITIAL_MOCK_JOBS));
  return INITIAL_MOCK_JOBS;
}

function saveMockJobs(jobs: any[]) {
  localStorage.setItem(MOCK_JOBS_KEY, JSON.stringify(jobs));
}

function getMockCandidates() {
  if (typeof localStorage === 'undefined') return INITIAL_MOCK_CANDIDATES;
  const data = localStorage.getItem(MOCK_CANDIDATES_KEY);
  if (!data) {
    localStorage.setItem(MOCK_CANDIDATES_KEY, JSON.stringify(INITIAL_MOCK_CANDIDATES));
    return INITIAL_MOCK_CANDIDATES;
  }
  try {
    let parsed = JSON.parse(data);
    if (Array.isArray(parsed) && parsed.length > 0) {
      // Ensure any candidates without client_id are assigned to Zool
      parsed = parsed.map((c: any) => ({
        ...c,
        client_id: c.client_id || DEFAULT_ZOOL_ID
      }));
      // Ensure Commit tenant has its candidates
      const hasCommit = parsed.some((c: any) => c.client_id === DEFAULT_COMMIT_ID);
      if (!hasCommit) {
        parsed.push(...INITIAL_MOCK_CANDIDATES.filter(c => c.client_id === DEFAULT_COMMIT_ID));
      }
      localStorage.setItem(MOCK_CANDIDATES_KEY, JSON.stringify(parsed));
      return parsed;
    }
  } catch (e) {}
  localStorage.setItem(MOCK_CANDIDATES_KEY, JSON.stringify(INITIAL_MOCK_CANDIDATES));
  return INITIAL_MOCK_CANDIDATES;
}

function saveMockCandidates(candidates: any[]) {
  localStorage.setItem(MOCK_CANDIDATES_KEY, JSON.stringify(candidates));
}

const MOCK_CLIENTS_KEY = 'hiremate_mock_clients';
const SEED_MOCK_CLIENTS = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    name: 'Zool',
    slug: 'zool',
    theme_color: '#2563eb',
    themeColor: '#2563eb',
    subscription_tier: 'pro',
    subscriptionTier: 'pro',
    created_at: new Date().toISOString(),
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    name: 'Commit',
    slug: 'commit',
    theme_color: '#f97316',
    themeColor: '#f97316',
    subscription_tier: 'enterprise',
    subscriptionTier: 'enterprise',
    created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    name: 'Nexus Tech Global',
    slug: 'nexus-tech',
    theme_color: '#10b981',
    themeColor: '#10b981',
    subscription_tier: 'enterprise',
    subscriptionTier: 'enterprise',
    created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    name: 'Horizon Innovations',
    slug: 'horizon',
    theme_color: '#8b5cf6',
    themeColor: '#8b5cf6',
    subscription_tier: 'pro',
    subscriptionTier: 'pro',
    created_at: new Date(Date.now() - 86400000 * 30).toISOString(),
  }
];

export function getMockClients() {
  if (typeof localStorage === 'undefined') return SEED_MOCK_CLIENTS;
  const data = localStorage.getItem(MOCK_CLIENTS_KEY);
  if (!data) {
    localStorage.setItem(MOCK_CLIENTS_KEY, JSON.stringify(SEED_MOCK_CLIENTS));
    return SEED_MOCK_CLIENTS;
  }
  try {
    let parsed = JSON.parse(data);
    if (Array.isArray(parsed) && parsed.length > 0) {
      // Ensure Zool and Commit are never missing
      if (!parsed.some((c: any) => c.slug === 'zool')) {
        parsed.unshift(SEED_MOCK_CLIENTS[0]);
      }
      if (!parsed.some((c: any) => c.slug === 'commit')) {
        parsed.splice(1, 0, SEED_MOCK_CLIENTS[1]);
      }
      localStorage.setItem(MOCK_CLIENTS_KEY, JSON.stringify(parsed));
      return parsed;
    }
  } catch (e) {}
  localStorage.setItem(MOCK_CLIENTS_KEY, JSON.stringify(SEED_MOCK_CLIENTS));
  return SEED_MOCK_CLIENTS;
}

export function saveMockClients(clients: any[]) {
  if (typeof localStorage === 'undefined') return;
  localStorage.setItem(MOCK_CLIENTS_KEY, JSON.stringify(clients));
}

// Helper to switch to mock mode
export function enableMockMode() {
  if (!useMock) {
    useMock = true;
    localStorage.setItem(USE_MOCK_SUPABASE_KEY, 'true');
    window.dispatchEvent(new Event('supabase_mock_mode_enabled'));
  }
}

// Check if mock mode is active
export function isMockMode() {
  return useMock;
}

// Check if we should disable mock mode (e.g. if explicitly cleared)
export function disableMockMode() {
  useMock = false;
  localStorage.removeItem(USE_MOCK_SUPABASE_KEY);
  localStorage.removeItem(MOCK_SESSION_KEY);
  window.dispatchEvent(new Event('supabase_mock_mode_disabled'));
}

// Check if current error is a network connectivity error
function isNetworkError(err: any): boolean {
  if (!err) return false;
  const msg = String(err.message || err).toLowerCase();
  return (
    msg.includes('failed to fetch') ||
    msg.includes('network error') ||
    msg.includes('load failed') ||
    msg.includes('dns') ||
    msg.includes('connection') ||
    msg.includes('unreachable') ||
    msg.includes('cors')
  );
}

// Local mock database helpers
function getMockUsers() {
  const data = localStorage.getItem(MOCK_USERS_KEY);
  return data ? JSON.parse(data) : [];
}

function saveMockUsers(users: any[]) {
  localStorage.setItem(MOCK_USERS_KEY, JSON.stringify(users));
}

function getMockProfiles() {
  const data = localStorage.getItem(MOCK_PROFILES_KEY);
  return data ? JSON.parse(data) : [];
}

function saveMockProfiles(profiles: any[]) {
  localStorage.setItem(MOCK_PROFILES_KEY, JSON.stringify(profiles));
}

function getMockRoles() {
  const data = localStorage.getItem(MOCK_ROLES_KEY);
  return data ? JSON.parse(data) : [];
}

function saveMockRoles(roles: any[]) {
  localStorage.setItem(MOCK_ROLES_KEY, JSON.stringify(roles));
}

function getMockSession() {
  const data = localStorage.getItem(MOCK_SESSION_KEY);
  return data ? JSON.parse(data) : null;
}

function setMockSession(user: any) {
  const session = {
    access_token: 'mock-access-token',
    token_type: 'bearer',
    expires_in: 3600,
    refresh_token: 'mock-refresh-token',
    user: user,
    expires_at: Math.floor(Date.now() / 1000) + 3600
  };
  localStorage.setItem(MOCK_SESSION_KEY, JSON.stringify(session));
}

function clearMockSession() {
  localStorage.removeItem(MOCK_SESSION_KEY);
}

function createMockUser(email: string, fullName: string, forcedRole?: string, forcedClientId?: string | null) {
  const isRootAdmin = email === 'admin@hiremate.ai' || email === 'srini@zool.in';
  const id = isRootAdmin ? (email === 'srini@zool.in' ? 'mock-srini-superadmin-id' : 'mock-admin-platform-id') : ('mock-user-id-' + Math.random().toString(36).substring(2, 11));
  const user = {
    id,
    aud: 'authenticated',
    role: 'authenticated',
    email,
    email_confirmed_at: new Date().toISOString(),
    phone: '',
    confirmed_at: new Date().toISOString(),
    last_sign_in_at: new Date().toISOString(),
    app_metadata: { provider: 'email', providers: ['email'] },
    user_metadata: { full_name: fullName },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  };

  const users = getMockUsers().filter((u: any) => u.email !== email);
  users.push(user);
  saveMockUsers(users);

  // Add profile
  const profiles = getMockProfiles().filter((p: any) => p.email !== email);
  profiles.push({
    id,
    email,
    full_name: fullName,
    avatar_url: `https://api.dicebear.com/7.x/adventurer/svg?seed=${encodeURIComponent(fullName)}`,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  });
  saveMockProfiles(profiles);

  // Add user role
  let roles = getMockRoles().filter((r: any) => r.user_id !== id);
  const role = forcedRole || (isRootAdmin ? 'super_admin' : (roles.length === 0 ? 'admin' : 'recruiter'));
  const emailLower = email.toLowerCase();
  const isCommitEmail = emailLower.includes('commit') || emailLower.includes('comm-it');
  const clientId = forcedClientId !== undefined
    ? forcedClientId
    : (isRootAdmin ? null : (isCommitEmail ? DEFAULT_COMMIT_ID : '00000000-0000-0000-0000-000000000001'));

  roles.push({
    id: isRootAdmin ? 'mock-role-platform-admin' : ('mock-role-id-' + Math.random().toString(36).substring(2, 11)),
    user_id: id,
    role,
    client_id: clientId,
    created_at: new Date().toISOString()
  });
  saveMockRoles(roles);

  return user;
}

let mockAuthListeners: any[] = [];
function triggerAuthChange(event: string, session: any) {
  mockAuthListeners.forEach(listener => {
    try {
      listener(event, session);
    } catch (e) {
      console.error('Error in auth state change listener:', e);
    }
  });
}

// Ensure platform admin, tenant admins, and recruiter accounts always exist in mock mode
const existingUsers = getMockUsers();
if (!existingUsers.some((u: any) => u.email === 'admin@hiremate.ai')) {
  createMockUser('admin@hiremate.ai', 'HireSort SuperAdmin', 'super_admin', null);
} else {
  // Ensure admin role is always super_admin
  const adminUser = existingUsers.find((u: any) => u.email === 'admin@hiremate.ai');
  const roles = getMockRoles();
  const existingRole = roles.find((r: any) => r.user_id === adminUser.id);
  if (!existingRole) {
    roles.push({
      id: 'mock-role-platform-admin',
      user_id: adminUser.id,
      role: 'super_admin',
      client_id: null,
      created_at: new Date().toISOString()
    });
    saveMockRoles(roles);
  } else if (existingRole.role !== 'super_admin' || existingRole.client_id !== null) {
    existingRole.role = 'super_admin';
    existingRole.client_id = null;
    saveMockRoles(roles);
  }
}

// Ensure srini@zool.in is always super_admin and client_id is null
const sriniExistingUser = existingUsers.find((u: any) => u.email === 'srini@zool.in');
if (sriniExistingUser) {
  const roles = getMockRoles();
  const sriniRole = roles.find((r: any) => r.user_id === sriniExistingUser.id);
  if (sriniRole) {
    sriniRole.role = 'super_admin';
    sriniRole.client_id = null;
    saveMockRoles(roles);
  }
}

// Commit tenant admin
if (!existingUsers.some((u: any) => u.email === 'admin@commit.com')) {
  createMockUser('admin@commit.com', 'Commit Workspace Admin', 'client_admin', DEFAULT_COMMIT_ID);
}

// Zool tenant admin
if (!existingUsers.some((u: any) => u.email === 'admin@zool.in')) {
  createMockUser('admin@zool.in', 'Zool Workspace Admin', 'client_admin', '00000000-0000-0000-0000-000000000001');
}

// Recruiter
if (!existingUsers.some((u: any) => u.email === 'recruiter@hiremate.ai')) {
  createMockUser('recruiter@hiremate.ai', 'Jane Recruiter', 'recruiter', '00000000-0000-0000-0000-000000000001');
}

// Self-heal: ensure any comm-it or commit mock accounts are mapped to Commit workspace
try {
  const mockProfiles = getMockProfiles();
  const mockRoles = getMockRoles();
  let changed = false;
  mockProfiles.forEach((p: any) => {
    const em = (p.email || '').toLowerCase();
    if (em.includes('commit') || em.includes('comm-it')) {
      const r = mockRoles.find((role: any) => role.user_id === p.id);
      if (r && r.client_id !== DEFAULT_COMMIT_ID) {
        r.client_id = DEFAULT_COMMIT_ID;
        changed = true;
      }
    }
  });
  if (changed) saveMockRoles(mockRoles);
} catch (e) {}

// Mock query builder to mimic postgrest
class MockQueryBuilder {
  table: string;
  filters: Array<(item: any) => boolean> = [];
  updateData: any = null;
  isDelete: boolean = false;
  isUpsert: boolean = false;
  orderFn: ((a: any, b: any) => number) | null = null;
  limitCount: number | null = null;

  constructor(table: string) {
    this.table = table;
  }

  select(columns?: string) {
    return this;
  }

  delete() {
    this.isDelete = true;
    return this;
  }

  order(column: string, options?: { ascending?: boolean }) {
    const asc = options?.ascending !== false;
    this.orderFn = (a: any, b: any) => {
      const valA = a[column];
      const valB = b[column];
      if (valA === valB) return 0;
      if (valA == null) return asc ? -1 : 1;
      if (valB == null) return asc ? 1 : -1;
      return asc ? (valA < valB ? -1 : 1) : (valA > valB ? -1 : 1);
    };
    return this;
  }

  limit(count: number) {
    this.limitCount = count;
    return this;
  }

  upsert(data: any) {
    this.updateData = Array.isArray(data) ? data : [data];
    this.isUpsert = true;
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push((item) => item[column] === value);
    return this;
  }

  neq(column: string, value: any) {
    this.filters.push((item) => item[column] !== value);
    return this;
  }

  in(column: string, values: any[]) {
    this.filters.push((item) => values.includes(item[column]));
    return this;
  }

  maybeSingle() {
    return this.execute().then(res => ({
      data: res.data && res.data.length > 0 ? res.data[0] : null,
      error: res.error
    }));
  }

  single() {
    return this.execute().then(res => {
      if (!res.data || res.data.length === 0) {
        return { data: null, error: new Error('No rows found') };
      }
      return { data: res.data[0], error: null };
    });
  }

  update(data: any) {
    this.updateData = Array.isArray(data) ? data[0] : data;
    return this;
  }

  insert(data: any) {
    this.updateData = Array.isArray(data) ? data[0] : data;
    this.filters = []; // clear filters for insert
    return this;
  }

  async execute() {
    if (this.isUpsert) {
      let tableData: any[] = [];
      let saveFn: (items: any[]) => void = () => {};
      if (this.table === 'jobs') { tableData = getMockJobs(); saveFn = saveMockJobs; }
      else if (this.table === 'candidates') { tableData = getMockCandidates(); saveFn = saveMockCandidates; }
      else if (this.table === 'clients') { tableData = getMockClients(); saveFn = saveMockClients; }
      else if (this.table === 'profiles') { tableData = getMockProfiles(); saveFn = saveMockProfiles; }
      else if (this.table === 'user_roles') { tableData = getMockRoles(); saveFn = saveMockRoles; }

      const itemsToUpsert = Array.isArray(this.updateData) ? this.updateData : [this.updateData];
      const resultItems: any[] = [];

      for (const item of itemsToUpsert) {
        const idx = tableData.findIndex((row: any) => 
          (item.id && row.id === item.id) || 
          (this.table === 'user_roles' && row.user_id === item.user_id)
        );
        if (idx >= 0) {
          tableData[idx] = { ...tableData[idx], ...item };
          resultItems.push(tableData[idx]);
        } else {
          const newItem = { 
            id: item.id || `${this.table.slice(0, 4)}-${Math.random().toString(36).substring(2, 9)}`, 
            ...item, 
            created_at: item.created_at || new Date().toISOString() 
          };
          tableData.push(newItem);
          resultItems.push(newItem);
        }
      }
      saveFn(tableData);
      return { data: resultItems, error: null };
    }

    if (this.isDelete) {
      let data: any[] = [];
      if (this.table === 'jobs') {
        let jobs = getMockJobs();
        if (this.filters.length > 0) {
          jobs = jobs.filter(j => {
            let matches = true;
            for (const filter of this.filters) {
              if (!filter(j)) matches = false;
            }
            return !matches;
          });
        } else {
          jobs = [];
        }
        saveMockJobs(jobs);
      } else if (this.table === 'candidates') {
        let candidates = getMockCandidates();
        if (this.filters.length > 0) {
          candidates = candidates.filter(c => {
            let matches = true;
            for (const filter of this.filters) {
              if (!filter(c)) matches = false;
            }
            return !matches;
          });
        } else {
          candidates = [];
        }
        saveMockCandidates(candidates);
      } else if (this.table === 'user_roles') {
        let roles = getMockRoles();
        if (this.filters.length > 0) {
          const adminUser = getMockUsers().find((u: any) => u.email === 'admin@hiremate.ai');
          const sriniUser = getMockUsers().find((u: any) => u.email === 'srini@zool.in');
          roles = roles.filter(r => {
            if (adminUser && r.user_id === adminUser.id) return true; // Protect root platform admin role
            if (sriniUser && r.user_id === sriniUser.id) return true; // Protect srini platform super admin role
            let matches = true;
            for (const filter of this.filters) {
              if (!filter(r)) matches = false;
            }
            return !matches;
          });
        }
        saveMockRoles(roles);
      } else if (this.table === 'profiles') {
        let profiles = getMockProfiles();
        if (this.filters.length > 0) {
          profiles = profiles.filter(p => {
            if (p.email === 'admin@hiremate.ai' || p.email === 'srini@zool.in') return true; // Protect platform super admin profiles
            let matches = true;
            for (const filter of this.filters) {
              if (!filter(p)) matches = false;
            }
            return !matches;
          });
        }
        saveMockProfiles(profiles);
      } else if (this.table === 'clients') {
        let clients = getMockClients();
        if (this.filters.length > 0) {
          clients = clients.filter(c => {
            // Protect base Zool workspace
            if (c.id === '00000000-0000-0000-0000-000000000001') return true;
            let matches = true;
            for (const filter of this.filters) {
              if (!filter(c)) matches = false;
            }
            return !matches;
          });
        }
        saveMockClients(clients);
      }
      return { data, error: null };
    }

    let data: any[] = [];
    if (this.table === 'profiles') {
      data = getMockProfiles();
    } else if (this.table === 'user_roles') {
      data = getMockRoles();
    } else if (this.table === 'jobs') {
      data = getMockJobs();
    } else if (this.table === 'candidates') {
      data = getMockCandidates();
    } else if (this.table === 'clients') {
      data = getMockClients();
    }

    if (this.updateData) {
      if (this.table === 'profiles') {
        let profiles = getMockProfiles();
        let updated = false;
        profiles = profiles.map(p => {
          let matches = this.filters.length > 0;
          for (const filter of this.filters) {
            if (!filter(p)) matches = false;
          }
          if (matches) {
            updated = true;
            return { ...p, ...this.updateData, updated_at: new Date().toISOString() };
          }
          return p;
        });

        if (!updated && this.filters.length === 0) {
          // Insert mode
          const newProfile = {
            id: this.updateData.id || 'mock-id-' + Math.random().toString(36).substring(2, 11),
            email: this.updateData.email || null,
            full_name: this.updateData.full_name || null,
            avatar_url: this.updateData.avatar_url || null,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString()
          };
          profiles.push(newProfile);
          data = [newProfile];
        } else {
          data = profiles.filter(p => {
            let matches = this.filters.length > 0;
            for (const filter of this.filters) {
              if (!filter(p)) matches = false;
            }
            return matches;
          });
        }
        saveMockProfiles(profiles);
      } else if (this.table === 'user_roles') {
        let roles = getMockRoles();
        let updated = false;
        roles = roles.map(r => {
          let matches = this.filters.length > 0;
          for (const filter of this.filters) {
            if (!filter(r)) matches = false;
          }
          if (matches) {
            updated = true;
            return { ...r, ...this.updateData };
          }
          return r;
        });

        if (!updated && this.filters.length === 0) {
          // Insert mode
          const newRole = {
            id: 'mock-role-id-' + Math.random().toString(36).substring(2, 11),
            user_id: this.updateData.user_id,
            role: this.updateData.role || 'recruiter',
            created_at: new Date().toISOString()
          };
          roles.push(newRole);
          data = [newRole];
        } else {
          data = roles.filter(r => {
            let matches = this.filters.length > 0;
            for (const filter of this.filters) {
              if (!filter(r)) matches = false;
            }
            return matches;
          });
        }
        saveMockRoles(roles);
      } else if (this.table === 'jobs') {
        let jobs = getMockJobs();
        let updated = false;
        jobs = jobs.map(j => {
          let matches = this.filters.length > 0;
          for (const filter of this.filters) {
            if (!filter(j)) matches = false;
          }
          if (matches) {
            updated = true;
            return { ...j, ...this.updateData };
          }
          return j;
        });

        if (!updated && this.filters.length === 0) {
          const payload = Array.isArray(this.updateData) ? this.updateData[0] : (this.updateData || {});
          const newJob = {
            id: payload.id || 'job-' + Math.random().toString(36).substring(2, 9),
            title: payload.title || 'Untitled Role',
            department: payload.department || 'Engineering',
            location: payload.location || 'Bangalore, India',
            type: payload.type || 'full-time',
            postedDate: new Date().toISOString().split('T')[0],
            screeningEndDate: payload.screeningEndDate || null,
            status: payload.status || 'active',
            candidateCount: 0,
            hireSortEnabled: payload.hire_sort_enabled !== undefined ? payload.hire_sort_enabled : true,
            description: payload.description || '',
            responsibilities: payload.responsibilities || [],
            requirements: payload.requirements || [],
            niceToHave: payload.nice_to_have || payload.niceToHave || [],
            salary: payload.salary || '₹25-40 LPA',
            isPublic: payload.is_public !== undefined ? payload.is_public : true,
            is_public: payload.is_public !== undefined ? payload.is_public : true,
            slug: payload.slug,
            created_by: payload.created_by || null,
            client_id: payload.client_id || DEFAULT_ZOOL_ID,
            predictiveEffectiveness: payload.predictiveEffectiveness || null
          };
          jobs.push(newJob);
          data = [newJob];
        } else {
          data = jobs.filter(j => {
            let matches = this.filters.length > 0;
            for (const filter of this.filters) {
              if (!filter(j)) matches = false;
            }
            return matches;
          });
        }
        saveMockJobs(jobs);
      } else if (this.table === 'candidates') {
        let candidates = getMockCandidates();
        let updated = false;
        candidates = candidates.map(c => {
          let matches = this.filters.length > 0;
          for (const filter of this.filters) {
            if (!filter(c)) matches = false;
          }
          if (matches) {
            updated = true;
            return { ...c, ...this.updateData };
          }
          return c;
        });

        if (!updated && this.filters.length === 0) {
          const payload = Array.isArray(this.updateData) ? this.updateData[0] : (this.updateData || {});
          const newCandidate = {
            id: payload.id || 'cand-' + Math.random().toString(36).substring(2, 9),
            name: payload.full_name || payload.name || 'Anonymous Applicant',
            full_name: payload.full_name || payload.name || 'Anonymous Applicant',
            email: payload.email || 'applicant@example.com',
            phone: payload.phone || null,
            job_id: payload.job_id,
            experience: Number(payload.experience) || 0,
            location: payload.location || 'Remote',
            appliedDate: new Date().toISOString().split('T')[0],
            matchedSkills: payload.matched_skills || payload.matchedSkills || [],
            missingSkills: payload.missing_skills || payload.missingSkills || [],
            aiScore: payload.ai_score || payload.aiScore || 'medium',
            cosineSimilarity: payload.cosine_similarity || payload.cosineSimilarity || 0.75,
            predictiveInsights: payload.predictive_insights || payload.predictiveInsights || {},
            resumeUrl: payload.resume_url || payload.resumeUrl || null,
            resumeText: payload.resume_text || payload.resumeText || ''
          };
          candidates.push(newCandidate);
          data = [newCandidate];
        } else {
          data = candidates.filter(c => {
            let matches = this.filters.length > 0;
            for (const filter of this.filters) {
              if (!filter(c)) matches = false;
            }
            return matches;
          });
        }
        saveMockCandidates(candidates);
      } else if (this.table === 'clients') {
        let clients = getMockClients();
        let updated = false;
        clients = clients.map(c => {
          let matches = this.filters.length > 0;
          for (const filter of this.filters) {
            if (!filter(c)) matches = false;
          }
          if (matches) {
            updated = true;
            return { ...c, ...this.updateData };
          }
          return c;
        });

        if (!updated && this.filters.length === 0) {
          const payload = Array.isArray(this.updateData) ? this.updateData[0] : (this.updateData || {});
          const newClient = {
            id: payload.id || 'client-' + Math.random().toString(36).substring(2, 9),
            name: payload.name || 'New Client',
            slug: payload.slug || 'client-' + Date.now(),
            logo_url: payload.logo_url || null,
            logoUrl: payload.logo_url || null,
            theme_color: payload.theme_color || '#2563eb',
            themeColor: payload.theme_color || '#2563eb',
            subscription_tier: payload.subscription_tier || 'pro',
            subscriptionTier: payload.subscription_tier || 'pro',
            created_at: new Date().toISOString()
          };
          clients.unshift(newClient);
          data = [newClient];
        } else {
          data = clients.filter(c => {
            let matches = this.filters.length > 0;
            for (const filter of this.filters) {
              if (!filter(c)) matches = false;
            }
            return matches;
          });
        }
        saveMockClients(clients);
      }
    } else {
      // Standard filter (select)
      if (this.filters.length > 0) {
        data = data.filter(item => {
          let matches = true;
          for (const filter of this.filters) {
            if (!filter(item)) matches = false;
          }
          return matches;
        });
      }
    }

    if (this.orderFn && Array.isArray(data)) {
      data = [...data].sort(this.orderFn);
    }

    if (typeof this.limitCount === 'number' && Array.isArray(data)) {
      data = data.slice(0, this.limitCount);
    }

    return { data, error: null };
  }

  then(onfulfilled?: any, onrejected?: any) {
    return this.execute().then(onfulfilled, onrejected);
  }
}

// Mock Supabase Client Object
const mockSupabase = {
  auth: {
    onAuthStateChange(callback: any) {
      mockAuthListeners.push(callback);
      const session = getMockSession();
      setTimeout(() => {
        callback(session ? 'SIGNED_IN' : 'INITIAL_SESSION', session);
      }, 0);
      return {
        data: {
          subscription: {
            unsubscribe() {
              mockAuthListeners = mockAuthListeners.filter(l => l !== callback);
            }
          }
        }
      };
    },
    async getSession() {
      return { data: { session: getMockSession() }, error: null };
    },
    async signInWithPassword({ email, password }: any) {
      if (!email.includes('@')) {
        return { data: { session: null, user: null }, error: new Error('Invalid email format') };
      }
      if (password.length < 6) {
        return { data: { session: null, user: null }, error: new Error('Password must be at least 6 characters') };
      }
      
      const users = getMockUsers();
      let user = users.find(u => u.email === email);
      if (!user) {
        // If email matches one of the seeded users but isn't registered, create it
        if (email === 'admin@hiremate.ai') {
          user = createMockUser('admin@hiremate.ai', 'HireSort SuperAdmin', 'super_admin', null);
        } else if (email === 'srini@zool.in') {
          user = createMockUser('srini@zool.in', 'Srini', 'super_admin', null);
        } else if (email === 'admin@commit.com') {
          user = createMockUser('admin@commit.com', 'Commit Workspace Admin', 'client_admin', DEFAULT_COMMIT_ID);
        } else if (/comm-?it/i.test(email)) {
          user = createMockUser(email, email.split('@')[0], 'admin', DEFAULT_COMMIT_ID);
        } else if (email === 'admin@zool.in') {
          user = createMockUser('admin@zool.in', 'Zool Workspace Admin', 'client_admin', '00000000-0000-0000-0000-000000000001');
        } else if (email === 'recruiter@hiremate.ai') {
          user = createMockUser('recruiter@hiremate.ai', 'Jane Recruiter', 'recruiter', '00000000-0000-0000-0000-000000000001');
        } else {
          // Allow automatic signup for any emails to make local dev super easy
          user = createMockUser(email, email.split('@')[0]);
        }
      }
      
      setMockSession(user);
      triggerAuthChange('SIGNED_IN', getMockSession());
      return { data: { session: getMockSession(), user }, error: null };
    },
    async signUp({ email, password, options }: any) {
      if (password.length < 6) {
        return { data: { session: null, user: null }, error: new Error('Password must be at least 6 characters') };
      }
      const users = getMockUsers();
      if (users.some(u => u.email === email)) {
        return { data: { session: null, user: null }, error: new Error('User already registered') };
      }
      
      const fullName = options?.data?.full_name || email.split('@')[0];
      const user = createMockUser(email, fullName);
      setMockSession(user);
      triggerAuthChange('SIGNED_IN', getMockSession());
      return { data: { session: getMockSession(), user }, error: null };
    },
    async signOut() {
      clearMockSession();
      triggerAuthChange('SIGNED_OUT', null);
      return { error: null };
    }
  },
  functions: {
    async invoke(functionName: string, options?: any) {
      if (functionName === 'delete-user') {
        const userId = options?.body?.userId;
        if (!userId) return { data: null, error: new Error('User ID required') };

        const adminUser = getMockUsers().find((u: any) => u.email === 'admin@hiremate.ai');
        if (adminUser && userId === adminUser.id) {
          return { data: null, error: new Error('Action prohibited: Root HireSort platform admin account cannot be deleted.') };
        }

        if (options?.body?.reassignJobsToUserId) {
          const targetId = options.body.reassignJobsToUserId;
          let jobs = getMockJobs().map((j: any) => {
            if (j.created_by === userId) {
              return { ...j, created_by: targetId };
            }
            return j;
          });
          saveMockJobs(jobs);
        }

        let profiles = getMockProfiles().filter(p => p.id !== userId);
        saveMockProfiles(profiles);

        let roles = getMockRoles().filter(r => r.user_id !== userId);
        saveMockRoles(roles);

        let users = getMockUsers().filter(u => u.id !== userId);
        saveMockUsers(users);

        return { data: { success: true }, error: null };
      }
      if (functionName === 'invite-user') {
        const { email, role, clientId } = options?.body || {};
        if (!email) return { data: null, error: new Error('Email required') };
        
        const existing = getMockUsers().find(u => u.email === email);
        if (existing) return { data: null, error: new Error('User already exists') };
        
        const user = createMockUser(email, email.split('@')[0], role);
        let roles = getMockRoles().map(r => r.user_id === user.id ? { ...r, role: role || 'recruiter', client_id: clientId || null } : r);
        saveMockRoles(roles);
        
        return { data: { success: true }, error: null };
      }
      return { data: { success: true }, error: null };
    }
  },
  from(table: string) {
    return new MockQueryBuilder(table);
  }
};

// Helper to wrap real database query builder chain
function wrapQueryBuilder(queryBuilder: any, table: string): any {
  return new Proxy(queryBuilder, {
    get(target: any, prop: string): any {
      const val = target[prop];
      if (typeof val === 'function') {
        return (...args: any[]) => {
          const res = val.apply(target, args);
          if (res && (typeof res === 'object' || typeof res === 'function')) {
            return wrapQueryBuilder(res, table);
          }
          return res;
        };
      }
      if (prop === 'then') {
        return (onfulfilled: any, onrejected: any) => {
          return target.then(
            (val: any) => {
              if (val && val.error && isNetworkError(val.error)) {
                console.warn(`Supabase query network error on ${table}, switching to mock mode.`, val.error);
                enableMockMode();
                return mockSupabase.from(table).execute().then(onfulfilled, onrejected);
              }
              return onfulfilled ? onfulfilled(val) : val;
            },
            (err: any) => {
              if (isNetworkError(err)) {
                console.warn(`Supabase query exception on ${table}, switching to mock mode.`, err);
                enableMockMode();
                return mockSupabase.from(table).execute().then(onfulfilled, onrejected);
              }
              return onrejected ? onrejected(err) : Promise.reject(err);
            }
          );
        };
      }
      return val;
    }
  });
}

// Proxied supabase client
export const supabase = new Proxy(realSupabase, {
  get(target: any, prop: string): any {
    if (useMock) {
      return (mockSupabase as any)[prop];
    }
    
    if (prop === 'auth') {
      return authProxy;
    }
    
    if (prop === 'from') {
      return (table: string) => {
        if (useMock) {
          return mockSupabase.from(table);
        }
        return wrapQueryBuilder(realSupabase.from(table), table);
      };
    }
    
    const val = target[prop];
    if (typeof val === 'function') {
      return (...args: any[]) => {
        try {
          const res = val.apply(target, args);
          if (res instanceof Promise) {
            return res.then((resolvedVal: any) => {
              if (resolvedVal && resolvedVal.error && isNetworkError(resolvedVal.error)) {
                console.warn("Supabase network error in response, switching to mock mode.", resolvedVal.error);
                enableMockMode();
                return (mockSupabase as any)[prop](...args);
              }
              return resolvedVal;
            }).catch((err) => {
              if (isNetworkError(err)) {
                console.warn("Supabase network error exception, switching to mock mode.", err);
                enableMockMode();
                return (mockSupabase as any)[prop](...args);
              }
              throw err;
            });
          }
          return res;
        } catch (err) {
          if (isNetworkError(err)) {
            console.warn("Supabase network error caught, switching to mock mode.", err);
            enableMockMode();
            return (mockSupabase as any)[prop](...args);
          }
          throw err;
        }
      };
    }
    return val;
  }
});

// Proxied auth client
const authProxy = new Proxy(realSupabase.auth, {
  get(target: any, prop: string): any {
    if (useMock) {
      return (mockSupabase.auth as any)[prop];
    }

    if (prop === 'onAuthStateChange') {
      return (callback: any) => {
        return realSupabase.auth.onAuthStateChange(callback);
      };
    }
    
    const val = target[prop];
    if (typeof val === 'function') {
      return (...args: any[]) => {
        try {
          const res = val.apply(target, args);
          if (res instanceof Promise) {
            return res.then((resolvedVal: any) => {
              if (resolvedVal && resolvedVal.error && isNetworkError(resolvedVal.error)) {
                console.warn("Supabase auth network error in response, switching to mock mode.", resolvedVal.error);
                enableMockMode();
                return (mockSupabase.auth as any)[prop](...args);
              }
              return resolvedVal;
            }).catch((err) => {
              if (isNetworkError(err)) {
                console.warn("Supabase auth network error exception, switching to mock mode.", err);
                enableMockMode();
                return (mockSupabase.auth as any)[prop](...args);
              }
              throw err;
            });
          }
          return res;
        } catch (err) {
          if (isNetworkError(err)) {
            console.warn("Supabase auth network error caught, switching to mock mode.", err);
            enableMockMode();
            return (mockSupabase.auth as any)[prop](...args);
          }
          throw err;
        }
      };
    }
    return val;
  }
});